version: '3.8'

services:
  api:
    build:
      context: .
    container_name: go-api
    hostname: go-api
    ports: 
      - "8080:3000"
    deploy:
      restart_policy:
        condition: unless-stopped
    networks:
      proxy:
  caddy:
    image: caddy:2-alpine
    container_name: reverse_proxy
    restart: unless-stopped
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS:?SITE_ADDRESS environment variable is not set}
    ports:
      - "80:80"
      - "443:443"  
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - api_caddy_data:/data # Optional
      - api_caddy_config:/config # Optional
    networks:
      proxy:
volumes:
  api_caddy_data:
  api_caddy_config:
networks:
  proxy: