apiVersion: apps/v1
kind: Deployment
metadata:
  name: squash-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: squash
  template:
    metadata:
      labels:
        app: squash
    spec:
      containers:
      - name: teams
        image: cicconee/squash:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: squash-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 8080
  selector:
    app: squash